# Basic
title: Always’Le
subtitle: 只要开始就会有新的可能
#welcome_message: <a href="http://swifter.tips" target="_blank">Swifter.tips - 我维护的 Swift 使用技巧分享网站，每周三更新，欢迎访问</a>
description: 嗨，我是张广，一个编程爱好者。深圳南山，求职ing。
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://alwaysle.com"

permalink: /:year/:month/:title/

# Format
highlighter: plain
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: purple

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: 项目, description: 我的项目, url: 'http://112.74.75.1/'}
    - {title: 关于, description: 了解更多关于我, url: 'http://about.alwaysle.com/'}
    - {title: 订阅, description: 邮件订阅本站, url: 'http://eepurl.com/wNSkj'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comments :
    disqus: guangzh

# Social
social:
    weibo: guangzh
    github: guangzh917
    twitter: guang_zh
    gplus: 100191423191340692282
    mail: guangzh917@gmail.com

# Google Analytics
ga:
    id: UA-73958897-1
    host: alwaysle.com
